title: Insights Results Aggregator
description: Aggregator service for Openshist insights results
baseurl: /insights-results-aggregator
url: "https://redhatinsights.github.io"
repository: "RedHatInsights/insights-results-aggregator"

heading_anchors: true
search_enabled: false

aux_links:
  "Github repository":
    - "https://github.com/RedHatInsights/insights-results-aggregator"

footer_content: "Copyright &copy; 2020 Red Hat, Inc.</a>"

# Build settings
# markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
