name: Go linters

on:
  pull_request:

jobs:
  golint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: ["1.20","1.21"]
        make-command: ["make fmt","make lint","make vet","make cyclo","make shellcheck","make errcheck","make goconst","make gosec","make ineffassign","make abcgo","make json-check"]
    name: Linters ${{ matrix.make-command }} for Go ${{ matrix.go-version}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build project
        run: go build
      - name: ${{ matrix.make-command[0] }}
        run: ${{ matrix.make-command }}
