name: Go linters

on:
  pull_request:

jobs:
  golint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go-version: ["1.20","1.21"]
        make-command: [{"name":"formatting","command":"make fmt"},{"name":"Go lint","command":"make lint"},{"name":"GO vet","command":"make vet"},{"name":"gocyclo","command":"make cyclo"},{"name":"shellcheck","command":"make shellcheck"},{"name":"errcheck","command":"make errcheck"},{"name":"goconst checker","command":"make goconst"},{"name":"gosec checker","command":"make gosec"},{"name":"ineffassign checker","command":"make ineffassign"},{"name":"goconst checker","command":"make goconst"},{"name":"gosec checker","command":"make gosec"},{"name":"ABC metrics checker","command":"make abcgo"},{"name":"JSON checker","command":"make json-check"}]
    name: ${{ matrix.make-command.name }} for Go ${{ matrix.go-version}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build project
        run: go build
      - name: ${{ matrix.make-command.name }}
        run: ${{ matrix.make-command.command }}
 